### ISSUE TITLE
Google search

### ISSUE THREAD

**Issue by suruaku** [meetDeveloper/Dictionary-Anywhere#18]
After using the extension for a while I noticed bunch of "define <word>" in googles' history. I assume the extension is just googling for the definition? Even though I saw you have made API for it. However it's pretty annoying when my google history is full of those define searcher because I use the extension a lot(it is really nice).

**Comment by meetDeveloper** [comment]
@suruaku Hmm, I never knew that history gets populated for that, which browser are you using?

**Comment by meetDeveloper** [comment]
@suruaku I am not using my API, as it might get rate limited because of upstream server, and I do not want user to suffer due to API rate limit.

**Comment by suruaku** [comment]
I am using Firefox 77.0.1 (64-bit) from snap on Ubuntu. History looks like [this.](https://i.imgur.com/TDvtcnx.png)

**Comment by meetDeveloper** [comment]
@suruaku I have fixed this in latest version, have updated extension to v1.0.3 Basically I have omitted credentials in fetch request so that cookie does not get send and that way now your history won't be affected. You can look at this [commit](https://github.com/meetDeveloper/Dictionary-Anywhere/commit/dc7ffb5e90e544e91abcb0e29d02b2745168c7ce)

**Comment by suruaku** [comment]
Awesome, it works. thanks a lot!

**Comment by meetDeveloper** [comment]
@suruaku Are you `poik444` on Mozilla Addons?
